spring: 
  application:
    name : toyProject
    
  datasource:
    url: jdbc:mysql://localhost:3306/proj3?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: datas
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none   # create, create-drop, update, validate 중 선택
    show-sql: false       # SQL 로그 출력 여부
    properties:
      hibernate:
        format_sql: true # SQL 보기 좋게 포맷팅
    database-platform: org.hibernate.dialect.MySQLDialect  #MySQL8Dialect 는 spring 2.0 이하에서 사용

  jwt:
    secretKey: practicekeyyyyyyyyyyyyyyyyyyyyyy
 

  #security:
   # oauth2:
   #   client:
      #  registration:
         # google:
            #client-id: {구글 클라이언트 ID}
            #client-secret: {구글 클라이언트 Secret}
            #scope: profile, email
        #provider:
          #google:
            #authorization-uri: https://accounts.google.com/o/oauth2/auth
            #token-uri: https://oauth2.googleapis.com/token
            #user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo  
        