spring: 
  application:
    name : toyProject
    
  datasource:
    url: jdbc:mysql://localhost:3306/proj3?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: datas
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create   # create, create-drop, update, validate 중 선택
    show-sql: true       # SQL 로그 출력 여부
    properties:
      hibernate:
        format_sql: true # SQL 보기 좋게 포맷팅
    database-platform: org.hibernate.dialect.MySQLDialect  #MySQL8Dialect 는 spring 2.0 이하에서 사용
